#-*- encoding:utf-8 -*-

KEY_ACTION_LIST = "KEY_ACTION_LIST"

KEY_ACTION_TASK_LIST = "KEY_ACTION_TASK_LIST"

# 事件
ACTION_SIGN = 1  # 签到事件
ACTION_LOGIN = 2 # 登录事件
ACTION_PALY = 3  # 游戏事项

ACTION_MAPPING = {
    ACTION_SIGN:[KEY_ACTION_TASK_LIST],
    ACTION_LOGIN:[KEY_ACTION_TASK_LIST],
}